/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gymgui;

import java.util.Date;

/**
 *
 * @author Niro Computers
 */
import java.util.*;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
public class RegisterEmp extends javax.swing.JDialog {

    /**
     * Creates new form RegisterEmp
     */
    public RegisterEmp(java.awt.Frame parent, boolean modal) throws SQLException, ClassNotFoundException {
        super(parent, modal);
        this.branches = getBranches();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sexes = new javax.swing.ButtonGroup();
        jLabel5 = new javax.swing.JLabel();
        clr_regE_btn = new javax.swing.JButton();
        start_date = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        emp_dept = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        emp_phone = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        emp_address = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        emp_fname = new javax.swing.JTextField();
        emp_lname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        m_emp = new javax.swing.JRadioButton();
        f_emp = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        discard_regE_btn = new javax.swing.JButton();
        emp_dob = new com.toedter.calendar.JDateChooser();
        registerE_btn1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        emp_branch = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Register new employee");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Enter the employee's start date:");

        clr_regE_btn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        clr_regE_btn.setText("Reset");
        clr_regE_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clr_regE_btnActionPerformed(evt);
            }
        });

        start_date.setDateFormatString("yyyy/MM/dd");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Choose the employee's department:");

        emp_dept.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Executives and Heads", "Human Resources", "Health and Paramedics", "Instructors/Trainers", "Others" }));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Enter employee's phone number:");

        emp_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_phoneActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Enter employee's address:");

        emp_address.setColumns(20);
        emp_address.setLineWrap(true);
        emp_address.setRows(5);
        emp_address.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emp_addressKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(emp_address);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Register a New Employee");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Enter the employee's full name:");

        emp_fname.setText("First Name");

        emp_lname.setText("Last name");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Enter the employee's sex:");

        sexes.add(m_emp);
        m_emp.setSelected(true);
        m_emp.setText("Male");
        m_emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_empActionPerformed(evt);
            }
        });

        sexes.add(f_emp);
        f_emp.setText("Female");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Enter the employee's date of birth:");

        discard_regE_btn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        discard_regE_btn.setText("Back");
        discard_regE_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discard_regE_btnActionPerformed(evt);
            }
        });

        emp_dob.setDateFormatString("yyyy/MM/dd");

        registerE_btn1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        registerE_btn1.setText("Register");
        registerE_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerE_btn1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Choose the employee's branch ID:");

        emp_branch.setModel(new DefaultComboBoxModel(this.branches));
        emp_branch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_branchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(emp_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(emp_lname, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(m_emp, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(f_emp, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(emp_branch, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(start_date, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(emp_dob, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(emp_dept, 0, 193, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(emp_phone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)))))
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(registerE_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(clr_regE_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(discard_regE_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(emp_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emp_lname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(m_emp)
                            .addComponent(f_emp)
                            .addComponent(jLabel3))
                        .addGap(20, 20, 20)
                        .addComponent(emp_dob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel4)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(start_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(emp_dept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(emp_branch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(emp_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clr_regE_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(discard_regE_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerE_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void clr_regE_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clr_regE_btnActionPerformed
        // TODO add your handling code here:
    emp_fname.setText("");
  emp_lname.setText("");
        //Date TODAY = new Date();
  emp_dob.setCalendar(null);
        start_date.setCalendar(null);
//        client_dob.setDate(TODAY);
//        join_date.setDate(TODAY);
        emp_branch.setSelectedIndex(0);
        emp_dept.setSelectedIndex(0);
        emp_phone.setText("");
        emp_address.setText("");

    }//GEN-LAST:event_clr_regE_btnActionPerformed

    private void emp_addressKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emp_addressKeyTyped
        // TODO add your handling code here:
        if(emp_address.getText().length()>=15){}
    }//GEN-LAST:event_emp_addressKeyTyped

    private void m_empActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_empActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_empActionPerformed

    private void discard_regE_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discard_regE_btnActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Home wind = new Home();
                wind.setVisible(true);
            }
        });

        this.dispose();
    }//GEN-LAST:event_discard_regE_btnActionPerformed

    private void registerE_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerE_btn1ActionPerformed
        Connection db = conn.getDB();
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
        String sqlstring = "INSERT INTO employee(efname, elname, edob, esex, estart_date, edep,ephone, eaddress, ebranch) VALUES(?,?,?,?,?,?,?,?,?)";
        try {
            PreparedStatement stmt = db.prepareStatement(sqlstring);
            stmt.setString(1, emp_fname.getText());
            stmt.setString(2, emp_lname.getText());
            stmt.setString(3, dateFormat.format(emp_dob.getDate()));
            stmt.setString(4, ((m_emp.isSelected())? "M": "F"));
            stmt.setString(5, dateFormat.format(start_date.getDate()));
            stmt.setString(6, emp_dept.getSelectedItem().toString());
            stmt.setString(7, emp_phone.getText());
            stmt.setString(8, emp_address.getText());
            stmt.setString(9, emp_branch.getSelectedItem().toString());
            stmt.executeUpdate();
            
          javax.swing.JOptionPane.showMessageDialog(rootPane, "New Employee is now registered sucessfully!");
          java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Home wind = new Home();
                wind.setVisible(true);
            }
        });
    
        this.dispose();
            


        } catch (Exception ex) {

            String msg = ex.toString();

            if(msg.contains("Null")) javax.swing.JOptionPane.showMessageDialog(rootPane, "Invalid Entry: all fields are required. Check you have filled all the fields correctly.");
            else if(msg.contains("dob_constraint2")) javax.swing.JOptionPane.showMessageDialog(rootPane, "Invalid DOB: Check the employee's date of birth and try again. They should be at least 18.");
            else if(msg.contains("trigger"))javax.swing.JOptionPane.showMessageDialog(rootPane, "Invalid start date: The employee's start date shouldn't \n 1. be earlier than the branch's opening date\n 2. later than today.");
            else javax.swing.JOptionPane.showMessageDialog(rootPane, "Error occured: Check your inputs and try again.");
           

           
            
            
//           if(ex.getMessage().contains("dob_constraint")){
//                      javax.swing.JOptionPane.showMessageDialog(rootPane, "Invalid DOB: Check the client's date of birth and try again.");
//
//           } 
//           else if (ex.toString().equals("java.lang.NullPointerException")){
//                    javax.swing.JOptionPane.showMessageDialog(rootPane, "Invalid Entry: all fields are required.");
//
//           }
           
            
        }
    }//GEN-LAST:event_registerE_btn1ActionPerformed

    private void emp_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_phoneActionPerformed

    private void emp_branchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_branchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_branchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RegisterEmp dialog;
                try {
                    dialog = new RegisterEmp(new javax.swing.JFrame(), true);
                
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);}
                catch (Exception ex) {
                    javax.swing.JOptionPane.showMessageDialog(null, "Something is wrong with the database!");
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clr_regE_btn;
    private javax.swing.JButton discard_regE_btn;
    private javax.swing.JTextArea emp_address;
    private javax.swing.JComboBox<String> emp_branch;
    private javax.swing.JComboBox<String> emp_dept;
    private com.toedter.calendar.JDateChooser emp_dob;
    private javax.swing.JTextField emp_fname;
    private javax.swing.JTextField emp_lname;
    private javax.swing.JTextField emp_phone;
    private javax.swing.JRadioButton f_emp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton m_emp;
    private javax.swing.JButton registerE_btn1;
    private javax.swing.ButtonGroup sexes;
    private com.toedter.calendar.JDateChooser start_date;
    // End of variables declaration//GEN-END:variables

    private DBConnection conn;
    private String[] branches;
    
    
    private String[] getBranches() throws SQLException, ClassNotFoundException {
       ArrayList<String> branches = new ArrayList<String>();
       String entry = "";
        try{conn = new DBConnection();
        Connection db = conn.getDB();
        Statement fetch = db.createStatement();
        ResultSet rs = fetch.executeQuery("SELECT bid FROM branch;");
        while(rs.next()){
        entry = rs.getInt("bid") + "";
        branches.add(entry);
        }}
        catch (Exception e){System.out.println(e);}
        return (String[]) branches.toArray(new String[branches.size()]);
        
    }}