/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gymgui;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Niro Computers
 */
public class RegisterProp extends javax.swing.JDialog {

    /**
     * Creates new form RegisterProp
     */
    public RegisterProp(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        try {
            branches = obj.getBranches();
            
            initComponents();
        } catch (SQLException ex) {
            Logger.getLogger(RegisterProp.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RegisterProp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        discard_regC_btn = new javax.swing.JButton();
        register_prop_btn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        reset_prop_btn = new javax.swing.JButton();
        purchase_date = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        prop_branch_id = new javax.swing.JComboBox<>();
        prop_model = new javax.swing.JTextField();
        prop_type = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        number = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Register property");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Enter the property type:");

        discard_regC_btn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        discard_regC_btn.setText("Back");
        discard_regC_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discard_regC_btnActionPerformed(evt);
            }
        });

        register_prop_btn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        register_prop_btn.setText("Register");
        register_prop_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_prop_btnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Enter property model:");

        reset_prop_btn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        reset_prop_btn.setText("Reset");
        reset_prop_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_prop_btnActionPerformed(evt);
            }
        });

        purchase_date.setDateFormatString("yyyy/MM/dd");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Select the ID of the branch the property belongs to:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Register a New Property");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Enter the purchase date of the property:");

        prop_branch_id.setModel(new DefaultComboBoxModel(this.branches));
        prop_branch_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prop_branch_idActionPerformed(evt);
            }
        });

        prop_model.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prop_modelActionPerformed(evt);
            }
        });

        prop_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prop_typeActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Number:");

        number.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(register_prop_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(reset_prop_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(discard_regC_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(95, 95, 95)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(purchase_date, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                            .addComponent(prop_model)
                            .addComponent(prop_type)
                            .addComponent(number)
                            .addComponent(prop_branch_id, 0, 0, Short.MAX_VALUE))
                        .addGap(69, 69, 69)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prop_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prop_model, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(purchase_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(prop_branch_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(register_prop_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reset_prop_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(discard_regC_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void discard_regC_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discard_regC_btnActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Home wind = new Home();
                wind.setVisible(true);
            }
        });

        this.dispose();
    }//GEN-LAST:event_discard_regC_btnActionPerformed

    private void register_prop_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_prop_btnActionPerformed
        // TODO add your handling code here:\
        try{
                conn = new DBConnection();
                Connection db = conn.getDB();
                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
                String query  = "INSERT INTO property(prop_type, prop_model, prop_purchase_date, number, prop_branch) VALUES(?, ?, ?, ?, ?);";
                PreparedStatement pstmnt = db.prepareStatement(query);
                pstmnt.setString(1, prop_type.getText());
                pstmnt.setString(2, prop_model.getText());
                pstmnt.setString(3, dateFormat.format(purchase_date.getDate()));
                pstmnt.setString(4,  number.getValue().toString());
                pstmnt.setString(5, prop_branch_id.getSelectedItem().toString());
                pstmnt.executeUpdate();
                
                  javax.swing.JOptionPane.showMessageDialog(rootPane, "Property is now registered sucessfully!");
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Home wind = new Home();
                wind.setVisible(true);
            }
        });

        this.dispose();
                
        }
        catch(Exception e){
        String msg  = e.toString();
        e.printStackTrace();
        if(msg.contains("NullPointer")) javax.swing.JOptionPane.showMessageDialog(rootPane, "All fields are required!");
        else javax.swing.JOptionPane.showMessageDialog(rootPane, "Unknown error occured.");
        }
        
        
        
        
        
      

    }//GEN-LAST:event_register_prop_btnActionPerformed

    private void reset_prop_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_prop_btnActionPerformed
        // TODO add your handling code here:
        prop_type.setText("");
        prop_model.setText("");
        number.setValue(1);
        purchase_date.setCalendar(null);
        prop_branch_id.setSelectedItem(2);
    }//GEN-LAST:event_reset_prop_btnActionPerformed

    private void prop_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prop_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prop_typeActionPerformed

    private void prop_modelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prop_modelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prop_modelActionPerformed

    private void prop_branch_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prop_branch_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prop_branch_idActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterProp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterProp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterProp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterProp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RegisterProp dialog = new RegisterProp(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton discard_regC_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner number;
    private javax.swing.JComboBox<String> prop_branch_id;
    private javax.swing.JTextField prop_model;
    private javax.swing.JTextField prop_type;
    private com.toedter.calendar.JDateChooser purchase_date;
    private javax.swing.JButton register_prop_btn;
    private javax.swing.JButton reset_prop_btn;
    // End of variables declaration//GEN-END:variables
    private DBConnection conn;
    private ShowClient obj = new ShowClient();
    private String[] branches;
//    private String[] branches;
//
//    
//    
//    private String[] getBranches() throws SQLException, ClassNotFoundException {
//       ArrayList<String> branches = new ArrayList<String>();
//       String entry = "";
//        try{conn = new DBConnection();
//        Connection db = conn.getDB();
//        Statement fetch = db.createStatement();
//        ResultSet rs = fetch.executeQuery("SELECT bid FROM branch;");
//        while(rs.next()){
//        entry = rs.getInt("bid") + "";
//        branches.add(entry);
//        }}
//        catch (Exception e){System.out.println(e);}
//        return (String[]) branches.toArray(new String[branches.size()]);
//}    
        
    
}
