/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gymgui;

import java.util.Date;
import javax.swing.table.DefaultTableModel;
import java.util.*;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Niro Computers
 */
public class RegisterProg extends javax.swing.JDialog {

    /**
     * Creates new form RegisterProg
     */
    public RegisterProg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        int cur = 5;
       d = new DefaultTableModel(cur+1,1){
  
       public boolean isCellEditable(int rows, int cols){ 
           if(rows == cur)
           return false;
       else return true;}
       
       };
       d.setValueAt("Last row", cur, 0);
       
       String[] idcol = {"Client ID"};
       d.setColumnIdentifiers(idcol);
       
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prog_end = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        discard_regP_btn = new javax.swing.JButton();
        prog_start = new com.toedter.calendar.JDateChooser();
        registerP_btn1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        clr_regP_btn = new javax.swing.JButton();
        prog_name = new javax.swing.JTextField();
        inst_id = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        part_id = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        no_part = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        prog_end.setDateFormatString("yyyy/MM/dd");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setText("Enter the programme's instructor ID");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("Enter the programme's start date:");

        discard_regP_btn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        discard_regP_btn.setText("Back");
        discard_regP_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discard_regP_btnActionPerformed(evt);
            }
        });

        prog_start.setDateFormatString("yyyy/MM/dd");

        registerP_btn1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        registerP_btn1.setText("Register");
        registerP_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerP_btn1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Register a New Programme");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setText("Enter the programme's end date:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Enter programme name:");

        clr_regP_btn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        clr_regP_btn.setText("Reset");
        clr_regP_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clr_regP_btnActionPerformed(evt);
            }
        });

        prog_name.setText("Workout Programme Name");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel10.setText("Enter the members' IDs that participate in this program:");

        part_id.setModel(d);
        jScrollPane1.setViewportView(part_id);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setText("Enter the number of participants:");

        no_part.setModel(new javax.swing.SpinnerNumberModel(5, 5, 20, 1));
        no_part.setToolTipText("");
        no_part.setValue(5);
        no_part.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                no_partStateChanged(evt);
            }
        });
        no_part.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                no_partPropertyChange(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel3.setText("Select the last row of the table and click on Register when you are done.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(prog_start, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(prog_name, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(inst_id, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(prog_end, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(no_part, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(registerP_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(27, 27, 27)
                                    .addComponent(clr_regP_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(42, 42, 42)
                                    .addComponent(discard_regP_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1)))))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(prog_name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(20, 20, 20)
                        .addComponent(prog_start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prog_end, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(inst_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(no_part, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(46, 46, 46)))
                .addGap(24, 24, 24)
                .addComponent(jLabel10)
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clr_regP_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(discard_regP_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerP_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void discard_regP_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discard_regP_btnActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Home wind = new Home();
                wind.setVisible(true);
            }
        });

        this.dispose();
    }//GEN-LAST:event_discard_regP_btnActionPerformed

    private void registerP_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerP_btn1ActionPerformed
        // TODO add your handling code here:
        try{
        conn = new DBConnection();
        Connection db = conn.getDB();
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
        String sqlstring = "INSERT INTO programme(prg_name, pstart_date, prg_end_date, prg_inst) VALUES(?,?,?,?);";
        
            PreparedStatement insert_smnt = db.prepareStatement(sqlstring);
            insert_smnt.setString(1, prog_name.getText());
            insert_smnt.setString(2, dateFormat.format(prog_start.getDate()));
            insert_smnt.setString(3, (prog_end.getCalendar()!=null)?(dateFormat.format(prog_end.getDate())): null);
            insert_smnt.setString(4, inst_id.getText());
            
            insert_smnt.executeUpdate();
            insert_smnt.close();
            ResultSet rs = db.createStatement().executeQuery("SELECT pid FROM programme WHERE prg_name = \"" + prog_name.getText() + "\";");
            rs.next();
            String pid = rs.getString("pid");
            
            
            String parts[] = new String[part_id.getRowCount()-1]; 
            int l = part_id.getRowCount()-1;
            for (int i = 0; i < l; i++) {
                parts[i] = part_id.getValueAt(i, 0).toString();
            }
        PreparedStatement insert_smnt2 = db.prepareStatement("INSERT INTO client_programme(cid,pid) VALUES(?, ?);");
            for (int i = 0; i < l; i++) {
            insert_smnt2.setString(1, parts[i]);
            insert_smnt2.setString(2, pid);
            insert_smnt2.executeUpdate();
           
            }
            insert_smnt2.close();


        javax.swing.JOptionPane.showMessageDialog(rootPane, "Programme is now registered sucessfully!");
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Home wind = new Home();
                wind.setVisible(true);
            }
        });

        this.dispose();



        }
        catch(Exception e){
        String msg = e.toString();
        //e.printStackTrace();
        String invalid_employee_id = "The program instructor should belong to the instructors/trainers department.";
        String invalid_date = "Error occured while parsing date: Check your date entries satisfy the following"
                + "\n 1. Programme start date is not later that programme end date."
                + "\n 2. Programme start date is not later than today."
                + "\n 3. Programme start date is not earlier than Instructor's start date.";
        if(msg.contains("invalid date")){javax.swing.JOptionPane.showMessageDialog(rootPane, invalid_date);}
        else if(msg.contains("invalid employee id")) javax.swing.JOptionPane.showMessageDialog(rootPane, invalid_employee_id);
        else if(msg.contains("Duplicate"))javax.swing.JOptionPane.showMessageDialog(rootPane, "There is already a programme with such name.");
        else if (msg.contains("NullPointerException")){
            try {
                javax.swing.JOptionPane.showMessageDialog(rootPane, "Make sure that all the fields are filled and that\n you have clicked the last row of the table.");
                conn = new DBConnection();
                Connection db = conn.getDB();
                PreparedStatement rs = db.prepareStatement("DELETE FROM programme WHERE prg_name = \"" + prog_name.getText() + "\";");
                rs.executeUpdate();
                rs.close();
            } catch (NullPointerException ex) {
               javax.swing.JOptionPane.showMessageDialog(rootPane, "Programme name is a required field.");
            } catch (Exception ex) {
               javax.swing.JOptionPane.showMessageDialog(rootPane, "Unknown Error occured.");;
            }
        }
        else javax.swing.JOptionPane.showMessageDialog(rootPane, "Unknown error occured. Check if all the client ID's exist.");
        }
        
        
        
        
        
        

    }//GEN-LAST:event_registerP_btn1ActionPerformed

    private void clr_regP_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clr_regP_btnActionPerformed
        // TODO add your handling code here:
        prog_name.setText("");
        Date TODAY = new Date();
        prog_start.setDate(TODAY);
        prog_end.setDate(TODAY);
//        emp_dept.setSelectedIndex(0);
        inst_id.setText("");
        no_part.setValue(5);
        DefaultTableModel init = new DefaultTableModel(5,1);
        String[] idcol = {"Client ID"};
       init.setColumnIdentifiers(idcol);
       part_id.setModel(init);
//        emp_branch.setSelectedIndex(0);
//        emp_phone.setText("");
//        emp_address.setText("");
    }//GEN-LAST:event_clr_regP_btnActionPerformed

    private void no_partPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_no_partPropertyChange
        // TODO add your handling code here:
       
    }//GEN-LAST:event_no_partPropertyChange

    private void no_partStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_no_partStateChanged
        // TODO add your handling code here
         int cur = (int) no_part.getValue();
       DefaultTableModel d = new DefaultTableModel(cur+1,1){
  
       public boolean isCellEditable(int rows, int cols){ 
           if(rows == cur)
           return false;
       else return true;}
       
       };
       d.setValueAt("Last row", cur, 0);
       
       String[] idcol = {"Client ID"};
       d.setColumnIdentifiers(idcol);
       
      
       
       part_id.setModel(d);
       
    }//GEN-LAST:event_no_partStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterProg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterProg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterProg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterProg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RegisterProg dialog = new RegisterProg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clr_regP_btn;
    private javax.swing.JButton discard_regP_btn;
    private javax.swing.JTextField inst_id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner no_part;
    private javax.swing.JTable part_id;
    private com.toedter.calendar.JDateChooser prog_end;
    private javax.swing.JTextField prog_name;
    private com.toedter.calendar.JDateChooser prog_start;
    private javax.swing.JButton registerP_btn1;
    // End of variables declaration//GEN-END:variables
private DBConnection conn;
private DefaultTableModel d;
}
