/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gymgui;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class UpdateProg extends javax.swing.JDialog {

    /**
     * Creates new form UpdateProg
     */
    public UpdateProg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        int cur = 1;
        d = new DefaultTableModel(cur+1,1){
  
       public boolean isCellEditable(int rows, int cols){ 
           if(rows == cur)
           return false;
       else return true;}
       
       };
        d.setValueAt("Last Row", cur, 0);
        String[] idcol = {"Client ID"};
        d.setColumnIdentifiers(idcol);
        try {
            programs = this.getProg();
        } catch (SQLException ex) {
            Logger.getLogger(UpdateProg.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(UpdateProg.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registerP_btn1 = new javax.swing.JButton();
        clr_regP_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        part_id = new javax.swing.JTable();
        discard_regP_btn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel10 = new javax.swing.JLabel();
        no_part = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        registerP_btn1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        registerP_btn1.setText("Register");
        registerP_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerP_btn1ActionPerformed(evt);
            }
        });

        clr_regP_btn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        clr_regP_btn.setText("Reset");
        clr_regP_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clr_regP_btnActionPerformed(evt);
            }
        });

        part_id.setModel(d);
        jScrollPane3.setViewportView(part_id);

        jScrollPane1.setViewportView(jScrollPane3);

        discard_regP_btn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        discard_regP_btn.setText("Back");
        discard_regP_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discard_regP_btnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setText("Enter the number of new participants:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Register New Members");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("Choose programme set:");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = programs;
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel10.setText("Enter the members' IDs that participate in this program:");

        no_part.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        no_part.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                no_partStateChanged(evt);
            }
        });
        no_part.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                no_partPropertyChange(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel3.setText("Select the last row of the table and click on Register when you are done.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(registerP_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(clr_regP_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(discard_regP_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel10)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(no_part, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(no_part, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addComponent(jLabel10)
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerP_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clr_regP_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(discard_regP_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void discard_regP_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discard_regP_btnActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Home wind = new Home();
                wind.setVisible(true);
            }
        });

        this.dispose();
    }//GEN-LAST:event_discard_regP_btnActionPerformed

    private void clr_regP_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clr_regP_btnActionPerformed
        // TODO add your handling code here:
        no_part.setValue(1);
        int cur = 1;
        DefaultTableModel init = new DefaultTableModel(cur + 1,1){
  
       public boolean isCellEditable(int rows, int cols){ 
           if(rows == cur)
           return false;
       else return true;}
       
       };
        String[] idcol = {"Client ID"};
        init.setColumnIdentifiers(idcol);
        part_id.setModel(init);
        //        emp_branch.setSelectedIndex(0);
        //        emp_phone.setText("");
        //        emp_address.setText("");
    }//GEN-LAST:event_clr_regP_btnActionPerformed

    private void registerP_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerP_btn1ActionPerformed
        // TODO add your handling code here:
        try{
            conn = new DBConnection();
            Connection db = conn.getDB();
            List<String> vals = jList1.getSelectedValuesList();
            int l = part_id.getRowCount()-1;
            String[] parts = new String[l];
            for (int i = 0; i < l; i++) {
                parts[i] = part_id.getValueAt(i, 0).toString();
            }
            PreparedStatement update_prog = db.prepareStatement("INSERT INTO client_programme(cid, pid) VALUES(?,?);");
            if (vals.size()>0){
                
                for (int i = 0; i <vals.size(); i++) {
                    for (int j = 0; j < l; j++) {
            update_prog.setString(1,parts[j]);
            update_prog.setString(2, vals.get(i));
            update_prog.executeUpdate();
           
            }
                    
                }
                update_prog.close();
             javax.swing.JOptionPane.showMessageDialog(rootPane, "Programme is now updated successfully!");
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                Home wind = new Home();
                wind.setVisible(true);
            }
        });

        this.dispose();
            }
            else{javax.swing.JOptionPane.showMessageDialog(rootPane, "Please select a program first.");}
            
            
           }
        catch(Exception e){
        String msg = e.toString();
        e.printStackTrace();
        
        
        if(msg.contains("Duplicate"))javax.swing.JOptionPane.showMessageDialog(rootPane, "Some of the clients already participate in the programme.");
        else if (msg.contains("NullPointerException")){
//                conn = new DBConnection();
//                Connection db = conn.getDB();
                javax.swing.JOptionPane.showMessageDialog(rootPane, "Make sure that you have clicked the last row of the table.");
//                PreparedStatement rs = db.prepareStatement("DELETE FROM programme WHERE prg_name = \"" + prog_name.getText() + "\";");
//                rs.executeUpdate();
//                rs.close();
            
        }
        else javax.swing.JOptionPane.showMessageDialog(rootPane, "Unknown error occured. Check if all the client ID's exist.");
        }
        
        
        
        
    
        
    }//GEN-LAST:event_registerP_btn1ActionPerformed
      
    private void no_partPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_no_partPropertyChange

    }//GEN-LAST:event_no_partPropertyChange

    private void no_partStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_no_partStateChanged
        // TODO add your handling code here:
        
                 int cur = (int) no_part.getValue();
       DefaultTableModel d = new DefaultTableModel(cur+1,1){
  
       public boolean isCellEditable(int rows, int cols){ 
           if(rows == cur)
           return false;
       else return true;}
       
       };
       d.setValueAt("Last row", cur, 0);
       
       String[] idcol = {"Client ID"};
       d.setColumnIdentifiers(idcol);
       
      
       
       part_id.setModel(d);
        
    }//GEN-LAST:event_no_partStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateProg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateProg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateProg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateProg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UpdateProg dialog = new UpdateProg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clr_regP_btn;
    private javax.swing.JButton discard_regP_btn;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner no_part;
    private javax.swing.JTable part_id;
    private javax.swing.JButton registerP_btn1;
    // End of variables declaration//GEN-END:variables
    private DBConnection conn;
    private String[] programs;
    private DefaultTableModel d;
     private String[] getProg() throws SQLException, ClassNotFoundException {
       ArrayList<String> progs = new ArrayList<String>();
       String entry = "";
        try{conn = new DBConnection();
        Connection db = conn.getDB();
        Statement fetch = db.createStatement();
        ResultSet rs = fetch.executeQuery("SELECT pid FROM programme;");
        while(rs.next()){
        entry = rs.getInt("pid") + "";
       progs.add(entry);
        }}
        catch (Exception e){javax.swing.JOptionPane.showMessageDialog(rootPane, "Error occured with the database.");}
        return (String[]) progs.toArray(new String[progs.size()]);
        
    }
    
}
